### PR TITLE
fix(ci): convert ci is failing due to perms

### PR DESCRIPTION
**Pull request by rchincha**
**What type of PR is this?**

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rchincha** [comment]
https://github.com/project-stacker/stacker/actions/runs/4360350946/jobs/7625179702

^ pls see.

**Comment by smoser** [comment]
If I understand this correctly this comes from tests/convert.bats which has `VOLUME /out` and then 'mkdir -p /out'.
Would it be an option to just change that to go to a different directory?

```bash
    cat > Dockerfile <<EOF
FROM alpine:3.16
VOLUME $HOME/out
...
```

It just seems odd to attempt that as an unprivileged user is not likely to be able to create and use a directory in /

**Comment by rchincha** [comment]
> If I understand this correctly this comes from tests/convert.bats which has `VOLUME /out` and then 'mkdir -p /out'. Would it be an option to just change that to go to a different directory?
> 
> ```shell
>     cat > Dockerfile <<EOF
> FROM alpine:3.16
> VOLUME $HOME/out
> ...
> ```
> 
> It just seems odd to attempt that as an unprivileged user is not likely to be able to create and use a directory in /

We could, but `stacker convert` would have no way to know what `docker -v <outside-container-volume>:<inside-mount>` the outside-container-volume would be. This is just so that we show we can be fully automated. But one is of course welcome to mangle the output of `stacker convert` and then mangle.

**Comment by smoser** [comment]
> > If I understand this correctly this comes from tests/convert.bats which has `VOLUME /out` and then 'mkdir -p /out'. Would it be an option to just change that to go to a different directory?
> > ```shell
> >     cat > Dockerfile <<EOF
> > FROM alpine:3.16
> > VOLUME $HOME/out
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It just seems odd to attempt that as an unprivileged user is not likely to be able to create and use a directory in /
> 
> We could, but `stacker convert` would have no way to know what `docker -v <outside-container-volume>:<inside-mount>` the outside-container-volume would be. This is just so that we show we can be fully automated. But one is of course welcome to mangle the output of `stacker convert` and then mangle.

just give an error:
```
Docker file 'Dockerfile'  not supported.  The provided Dockerfile contains a VOLUME entry for '/out'.
/out is not writable by the current user.  Please modify the Dockerfile to contain a writable path for
the given VOLUME.
```

**Review by smoser — APPROVED** [review]
I think this is really good. Thanks.

The only comment i have is that I would suggest processing command line arguments in order rather than always giving precedence to '--substitute' over contents of '--substitute-file'.

That allows the caller to get whatever behavior they want (perhaps they just want to append a '--substitute-file' onto an existing command line with --substitute and have it override).

its not a big thing, due to the "static" nature of the substitute-file, so i'll approve but you're welcome to change that too.

**Pull request merged**
