### PR TITLE
fix: added build-base to package list for static build

### LINKED ISSUE #473: Bug: alpine:edge aarch64 image doesn't compile c-programs
### stacker version

b895c90

### Describe the bug

When running build.yaml in a container, the alpine:edge image for aarch64 doesn't seem to compile C-programs properly (see screenshot below).

### To reproduce

Simply ran `make` in stacker repo on an ampere server (aarch64).

### Expected behavior

Alpine image should be able to build and link C programs in aarch64.

### Screenshots

Screenshot 2023-07-05 at 3 56 08 PM

### Additional context

@raharper found a fix which enabled the script to finish and compile all the C programs, I'll submit a pr for this shortly

### PR DESCRIPTION
**Pull request by ashwing123**
**What type of PR is this?**
bug

**Which issue does this PR fix**:
fixes #473

**What does this PR do / Why do we need it**:
Enables alpine:edge aarch64 image to finish building (allows it to compile C programs).

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Signed-off-by: Ashwin Gopalan ashwin.gopalan02@gmail.com

### CODE REVIEW

**Comment by ashwing123** [comment]
Added commit message and PR description/subject changes

**Review by hallyn — APPROVED** [review]
Thanks!

**Comment by hallyn** [comment]
Note this is not currently mergeable as "The base branch requires all commits to be signed"

**Comment by ashwing123** [comment]
Ah might be because of the sync fork I got rid of. I'll go back and amend that commit.

**Pull request merged**
