### PR TITLE
test: add busybox image, use it to replace centos image.

### PR DESCRIPTION
**Pull request by smoser**
This is basically the add of BUSYBOX image and then using that instead of centos image.

**What type of PR is this?**

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by smoser** [comment]
Just for some reference here...
The last action to run against main [here](https://github.com/project-stacker/stacker/actions/runs/6835905299/job/18590213127) took 21m29s for unpriv 'Test' section and 24m39s for priv.

The action for *this* pr [here](https://github.com/project-stacker/stacker/actions/runs/6854694646/job/18638163347) took 4m14 seconds for unpriv and 8m21s for priv.

**Comment by smoser** [comment]
@rchincha , do you have thoughts on this? From my perspective, it is an obvious huge win. It reduces the longest poll in the c-i tent (priv=priv workflow=ci) by ~ 40% ([37m3s](https://github.com/project-stacker/stacker/actions/runs/6835905299/job/18590213212) to [23m11s](https://github.com/project-stacker/stacker/actions/runs/6854694646/job/18638163532)

**Comment by rchincha** [comment]
> @rchincha , do you have thoughts on this? From my perspective, it is an obvious huge win. It reduces the longest poll in the c-i tent (priv=priv workflow=ci) by ~ 40% ([37m3s](https://github.com/project-stacker/stacker/actions/runs/6835905299/job/18590213212) to [23m11s](https://github.com/project-stacker/stacker/actions/runs/6854694646/job/18638163532)) and specifically the 'test' action of that run from 24m39s to 8m21s (~66%).
> 
> I'm not opposed to using centos (or some other image that is a more "real world" use case) for a set of tests, but it appears to be just wasted IO for the most part here.

Large multi-layer images cover some cases (such as sizes, compression, etc)
But we can move that into nightly tests. 
When invoked from ci, maybe use the smaller images and nightly larger ones?

**Comment by smoser** [comment]
> Large multi-layer images cover some cases (such as sizes, compression, etc)

Centos is not a multi-layer image.

**Review by rchincha — APPROVED** [review]
lgtm

**Pull request merged**
